DROP TABLE IF EXISTS person;

CREATE TABLE person (
       id BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
       name  VARCHAR(255) NOT NULL UNIQUE,
       image_id  VARCHAR(255) NOT NULL UNIQUE
);